Vagrant.configure("2") do |config|
    # ubuntu
    config.vm.define "ubuntu" do |vps|
        vps.vm.box = "ubuntu/jammy64" # https://app.vagrantup.com/ubuntu/boxes/jammy64, # https://releases.ubuntu.com/
        vps.vm.hostname = "ubuntu"
        vps.vm.network "private_network", ip: "172.14.15.100"
        vps.vm.provider "virtualbox" do |virtualbox|
            virtualbox.name = "ubuntu"
            virtualbox.memory = 2048
            virtualbox.cpus = 2
        end
    end

	# automatically installed and configured when the machine is created
    config.vm.provision "file", source: "#{Dir.home}/.ssh/id_ed25519", destination: "/tmp/id_ed25519"
    config.vm.provision "shell" do |shell|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ed25519.pub").first.strip
        shell.inline = <<-SHELL
        # Create kukun user
        useradd -s /bin/bash -d /home/kukun/ -m -G sudo kukun
        echo 'kukun ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

        # User kukun
        mkdir -p /home/kukun/.ssh
        echo #{ssh_pub_key} >> /home/kukun/.ssh/authorized_keys
        cp /tmp/id_ed25519 /home/kukun/.ssh/id_ed25519
        chown -R kukun:kukun /home/kukun/.ssh
        chmod -R 0600 /home/kukun/.ssh/id_ed25519

        # User ubuntu
        mkdir -p /home/ubuntu/.ssh
        echo #{ssh_pub_key} >> /home/ubuntu/.ssh/authorized_keys
        cp /tmp/id_ed25519 /home/ubuntu/.ssh/id_ed25519
        chown -R ubuntu:ubuntu /home/ubuntu/.ssh
        chmod -R 0600 /home/ubuntu/.ssh/id_ed25519

        # User Root
        mkdir -p /root/.ssh
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        cp /tmp/id_ed25519 /root/.ssh/id_ed25519
        chmod -R 0600 /root/.ssh/id_ed25519

        rm -f /tmp/id_ed25519
        SHELL
    end
end
