- hosts: all
  name: (#4) Setup All hosts
  remote_user: ubuntu
  become: yes
  tasks:
    - name: (#9) Update the apt package index and install packages to allow apt to use a repository over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: yes

    - name: (#46) Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: (#51) Get Ubuntu release version
      command: lsb_release -cs
      register: ubuntu_version

    - name: (#55) Get architecture
      command: dpkg --print-architecture
      register: architecture

    - name: (#59) Add Docker repository
      apt_repository:
        repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present
        filename: docker

    - name: (#65) Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: (#68) Install Docker Engine, containerd, and Docker Compose.
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        state: present
        update_cache: yes


    - name: (#27) Copy foder docker/aws/usr  Docker to EC2
      copy:
        src: ../haproxy
        dest: /home/ubuntu
        force: yes
        mode: '0755'
