services:
  multi-platform:
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    restart: always
    ports:
      - '6001:80'
    platform:
      linux/amd64
