services:
  multi-platform:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
