- hosts: all
  name: (#4) Setup All hosts
  remote_user: kukun
  become: yes
  tasks:
    - name: (#9) Update the apt package index and install packages to allow apt to use a repository over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
          - build-essential
        state: present
        update_cache: yes

    - name: (#46) Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: (#51) Get Debian release version
      command: lsb_release -cs
      register: debian_version

    - name: (#55) Get architecture
      command: dpkg --print-architecture
      register: architecture

    - name: (#59) Add Docker repository
      apt_repository:
        repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/debian {{ debian_version.stdout }} stable"
        state: present
        filename: docker

    - name: (#65) Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: (#68) Install Docker Engine, containerd, and Docker Compose.
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Install Rust
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Reload PATH environment variable to include
      shell: source $HOME/.cargo/env