version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    platform: wasi/wasm32
    runtime: io.containerd.wasmedge.v1
    ports:
      - "8081:80"